---
  host: "127.0.0.1"
  port: 3000
  domain: "api.drivers.uz"
  log_file: "logs/vt.log"
  log_level: "debug" #info, warn, error
  gcm_api_key: "gcm_api_key"
  twilio_sid: "twilio_sid"
  twilio_token: "twilio_token"
  postgresql: 
    host: "db.drivers.uz"
    port: 5432
    user: "vt"
    pass: "vtvtvtvt"
    name: "vt"
    pool_size: 200
  redis: 
    host: "qm.drivers.uz"
    port: 6379
    auth:
    db: 0
